export const recentOrders = [
    {
      orderId: 'ORD001',
      productName: 'Product A',
      units: '3',
      orderDate: new Date('2023-05-25'),
      orderCost: '$50',
      status: 'Processing',
    },
    {
      orderId: 'ORD002',
      productName: 'Product B',
      units: '1',
      orderDate: new Date('2023-05-24'),
      orderCost: '$20',
      status: 'Delivered',
    },
    {
      orderId: 'ORD003',
      productName: 'Product C',
      units: '2',
      orderDate: new Date('2023-05-23'),
      orderCost: '$35',
      status: 'Cancelled',
    },
    {
      orderId: 'ORD004',
      productName: 'Product D',
      units: '5',
      orderDate: new Date('2023-05-22'),
      orderCost: '$75',
      status: 'Processing',
    },
    {
      orderId: 'ORD005',
      productName: 'Product E',
      units: '1',
      orderDate: new Date('2023-05-21'),
      orderCost: '$15',
      status: 'Delivered',
    },
    {
      orderId: 'ORD006',
      productName: 'Product F',
      units: '4',
      orderDate: new Date('2023-05-20'),
      orderCost: '$60',
      status: 'Processing',
    },
    {
      orderId: 'ORD007',
      productName: 'Product G',
      units: '2',
      orderDate: new Date('2023-05-19'),
      orderCost: '$30',
      status: 'Delivered',
    },
    {
      orderId: 'ORD008',
      productName: 'Product H',
      units: '3',
      orderDate: new Date('2023-05-18'),
      orderCost: '$45',
      status: 'Processing',
    },
    {
      orderId: 'ORD009',
      productName: 'Product I',
      units: '1',
      orderDate: new Date('2023-05-17'),
      orderCost: '$25',
      status: 'Delivered',
    },
    {
      orderId: 'ORD010',
      productName: 'Product J',
      units: '2',
      orderDate: new Date('2023-05-16'),
      orderCost: '$40',
      status: 'Processing',
    },
    {
      orderId: 'ORD011',
      productName: 'Product K',
      units: '3',
      orderDate: new Date('2023-05-15'),
      orderCost: '$55',
      status: 'Delivered',
    },
    {
      orderId: 'ORD012',
      productName: 'Product L',
      units: '1',
      orderDate: new Date('2023-05-14'),
      orderCost: '$20',
      status: 'Processing',
    },
    {
      orderId: 'ORD013',
      productName: 'Product M',
      units: '4',
      orderDate: new Date('2023-05-13'),
      orderCost: '$65',
      status: 'Delivered',
    },
    {
      orderId: 'ORD014',
      productName: 'Product N',
      units: '2',
      orderDate: new Date('2023-05-12'),
      orderCost: '$30',
      status: 'Cancelled',
    },
    {
      orderId: 'ORD015',
      productName: 'Product O',
      units: '3',
      orderDate: new Date('2023-05-11'),
      orderCost: '$45',
      status: 'Processing',
    }
  ];
  
  export const newCustomers = [
    {
      imgSrc: 'customer1.jpg',
      name: 'John Doe',
      noOfOrders: '3',
      amount: '$150',
    },
    {
      imgSrc: 'customer2.jpg',
      name: 'Jane Smith',
      noOfOrders: '1',
      amount: '$50',
    },
    {
      imgSrc: 'customer3.jpg',
      name: 'David Johnson',
      noOfOrders: '2',
      amount: '$100',
    },
    {
      imgSrc: 'customer4.jpg',
      name: 'Emily Davis',
      noOfOrders: '1',
      amount: '$50',
    },
    {
      imgSrc: 'customer5.jpg',
      name: 'Michael Brown',
      noOfOrders: '4',
      amount: '$200',
    },
    {
      imgSrc: 'customer6.jpg',
      name: 'Olivia Miller',
      noOfOrders: '2',
      amount: '$100',
    },
    {
      imgSrc: 'customer7.jpg',
      name: 'William Wilson',
      noOfOrders: '1',
      amount: '$50',
    },
    {
      imgSrc: 'customer8.jpg',
      name: 'Sophia Anderson',
      noOfOrders: '3',
      amount: '$150',
    },
    {
      imgSrc: 'customer9.jpg',
      name: 'James Martin',
      noOfOrders: '2',
      amount: '$100',
    },
    {
      imgSrc: 'customer10.jpg',
      name: 'Isabella Thompson',
      noOfOrders: '1',
      amount: '$50',
    },
    {
      imgSrc: 'customer11.jpg',
      name: 'Alexander Garcia',
      noOfOrders: '4',
      amount: '$200',
    },
    {
      imgSrc: 'customer12.jpg',
      name: 'Mia Martinez',
      noOfOrders: '2',
      amount: '$100',
    },
  ];
  
  
  export const topProducts = [
    {
      imgSrc: 'product1.jpg',
      title: 'Product A',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      price: '$49.99',
      oldPrice: '$59.99',
      noOfSales: '15',
    },
    {
      imgSrc: 'product2.jpg',
      title: 'Product B',
      description: 'Pellentesque ac ligula in tellus faucibus ullamcorper.',
      price: '$29.99',
      oldPrice: '$39.99',
      noOfSales: '8',
    },
    {
      imgSrc: 'product3.jpg',
      title: 'Product C',
      description: 'Nulla aliquet risus eget felis gravida, a fringilla purus tempor.',
      price: '$19.99',
      oldPrice: '$24.99',
      noOfSales: '12',
    },
    {
      imgSrc: 'product4.jpg',
      title: 'Product D',
      description: 'Sed congue felis vel commodo volutpat.',
      price: '$39.99',
      oldPrice: '$49.99',
      noOfSales: '10',
    },
    {
      imgSrc: 'product5.jpg',
      title: 'Product E',
      description: 'Vestibulum pulvinar mauris sit amet tincidunt volutpat.',
      price: '$59.99',
      oldPrice: '$69.99',
      noOfSales: '5',
    },
    {
      imgSrc: 'product6.jpg',
      title: 'Product F',
      description: 'Fusce eget augue ac justo mattis hendrerit vitae in sapien.',
      price: '$34.99',
      oldPrice: '$44.99',
      noOfSales: '20',
    },
    {
      imgSrc: 'product7.jpg',
      title: 'Product G',
      description: 'Nunc tincidunt metus eu purus lacinia, sed iaculis nulla tristique.',
      price: '$24.99',
      oldPrice: '$29.99',
      noOfSales: '7',
    },
    {
      imgSrc: 'product8.jpg',
      title: 'Product H',
      description: 'Aenean fringilla elit a sollicitudin commodo.',
      price: '$44.99',
      oldPrice: '$54.99',
      noOfSales: '18',
    },
    {
      imgSrc: 'product9.jpg',
      title: 'Product I',
      description: 'Phasellus pretium enim ut ligula convallis, vitae tristique mauris ullamcorper.',
      price: '$49.99',
      oldPrice: '$59.99',
      noOfSales: '13',
    },
    {
      imgSrc: 'product10.jpg',
      title: 'Product J',
      description: 'Maecenas tincidunt risus id gravida interdum.',
      price: '$29.99',
      oldPrice: '$39.99',
      noOfSales: '9',
    },
    {
      imgSrc: 'product11.jpg',
      title: 'Product K',
      description: 'Donec tempus ligula ut erat pretium finibus.',
      price: '$19.99',
      oldPrice: '$24.99',
      noOfSales: '11',
    },
    {
      imgSrc: 'product12.jpg',
      title: 'Product L',
      description: 'Morbi commodo mauris sed sapien fringilla, nec vestibulum nunc mattis.',
      price: '$39.99',
      oldPrice: '$49.99',
      noOfSales: '16',
    },
  ];
  